services:
  - type: web
    name: prahari-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && python -m app.database.seed"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./prahari.db
      - key: FRONTEND_URL
        value: "https://prahari-frontend-6wa3.onrender.com"
  
  - type: static
    name: prahari-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: "https://prahari-backend.onrender.com"
      - key: VITE_API_BASE_URL
        value: "https://prahari-backend.onrender.com"
